project_id = "dkhpfwgejjyheixkpvpr"

[functions.public-asset]
verify_jwt = false

[functions.ingest-file]
verify_jwt = true

[functions.create-entanglement]
verify_jwt = true

[functions.ascribe-data]
verify_jwt = true
