-- Add 360 view settings to spaces table
ALTER TABLE public.spaces
ADD COLUMN IF NOT EXISTS show_360 BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS x_axis_offset NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS y_axis_offset NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS volume NUMERIC DEFAULT 50,
ADD COLUMN IF NOT EXISTS is_muted BOOLEAN DEFAULT true;